### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by AXXXX2324** [insomniacslk/python-dublin-traceroute#11] opened 2018-04-24 10:05 UTC
pip install dublintraceroute
Collecting dublintraceroute
  Using cached https://files.pythonhosted.org/packages/9a/de/2fdb40e580b2e56ca914f7c6c71cd57c11e59ab79c1b988b8f550b122ca1/dublintraceroute-0.4.2.tar.gz
Building wheels for collected packages: dublintraceroute
  Running setup.py bdist_wheel for dublintraceroute ... error
  Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9fw10nzg/dublintraceroute/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-3kk0j25a --python-tag cp36:
  /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_requires'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/dublintraceroute
  copying dublintraceroute/tracerouteresults.py -> build/lib.linux-x86_64-3.6/dublintraceroute
  copying dublintraceroute/__init__.py -> build/lib.linux-x86_64-3.6/dublintraceroute
  copying dublintraceroute/dublintraceroute.py -> build/lib.linux-x86_64-3.6/dublintraceroute
  copying dublintraceroute/__main__.py -> build/lib.linux-x86_64-3.6/dublintraceroute
  running build_ext
  building 'dublintraceroute._dublintraceroute' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/dublintraceroute
  creating build/temp.linux-x86_64-3.6/dublintraceroute/py3
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../include -I/usr/include/jsoncpp -I/usr/local/include/python3.6m -c dublintraceroute/py3/_dublintraceroute.cc -o build/temp.linux-x86_64-3.6/dublintraceroute/py3/_dublintraceroute.o -std=c++11 -ldublintraceroute
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  dublintraceroute/py3/_dublintraceroute.cc: In function ‘PyObject* DublinTraceroute_traceroute(PyObject*, PyObject*)’:
  dublintraceroute/py3/_dublintraceroute.cc:94:11: error: no match for ‘operator=’ (operand types are ‘std::shared_ptr<TracerouteResults>’ and ‘TracerouteResults’)
     results = dublintraceroute->traceroute();
             ^
  dublintraceroute/py3/_dublintraceroute.cc:94:11: note: candidates are:
  In file included from /usr/include/c++/4.8.2/memory:82:0,
                   from /usr/include/c++/4.8.2/thread:40,
                   from /usr/include/dublintraceroute/dublin_traceroute.h:19,
                   from dublintraceroute/py3/_dublintraceroute.cc:4:
  /usr/include/c++/4.8.2/bits/shared_ptr.h:268:19: note: std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = TracerouteResults]
         shared_ptr& operator=(const shared_ptr&) noexcept = default;
                     ^
  /usr/include/c++/4.8.2/bits/shared_ptr.h:268:19: note:   no known conversion for argument 1 from ‘TracerouteResults’ to ‘const std::shared_ptr<TracerouteResults>&’
  /usr/include/c++/4.8.2/bits/shared_ptr.h:272:2: note: template<class _Tp1> std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp1>&) [with _Tp1 = _Tp1; _Tp = TracerouteResults]
    operator=(const shared_ptr<_Tp1>& __r) noexcept
    ^
  /usr/include/c++/4.8.2/bits/shared_ptr.h:272:2: note:   template argument deduction/substitution failed:
  dublintraceroute/py3/_dublintraceroute.cc:94:11: note:   ‘TracerouteResults’ is not derived from ‘const std::shared_ptr<_Tp1>’
     results = dublintraceroute->traceroute();
             ^
  In file included from /usr/include/c++/4.8.2/memory:82:0,
                   from /usr/include/c++/4.8.2/thread:40,
                   from /usr/include/dublintraceroute/dublin_traceroute.h:19,
                   from dublintraceroute/py3/_dublintraceroute.cc:4:
  /usr/include/c++/4.8.2/bits/shared_ptr.h:281:2: note: template<class _Tp1> std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Tp1 = _Tp1; _Tp = TracerouteResults]
    operator=(std::auto_ptr<_Tp1>&& __r)
    ^
  /usr/include/c++/4.8.2/bits/shared_ptr.h:281:2: note:   template argument deduction/substitution failed:
  dublintraceroute/py3/_dublintraceroute.cc:94:11: note:   ‘TracerouteResults’ is not derived from ‘std::auto_ptr<_Up>’
     results = dublintraceroute->traceroute();
             ^
  In file included from /usr/include/c++/4.8.2/memory:82:0,
                   from /usr/include/c++/4.8.2/thread:40,
                   from /usr/include/dublintraceroute/dublin_traceroute.h:19,
                   from dublintraceroute/py3/_dublintraceroute.cc:4:
  /usr/include/c++/4.8.2/bits/shared_ptr.h:289:7: note: std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = TracerouteResults]
         operator=(shared_ptr&& __r) noexcept
         ^
  /usr/include/c++/4.8.2/bits/shared_ptr.h:289:7: note:   no known conversion for argument 1 from ‘TracerouteResults’ to ‘std::shared_ptr<TracerouteResults>&&’
  /usr/include/c++/4.8.2/bits/shared_ptr.h:297:2: note: template<class _Tp1> std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp1>&&) [with _Tp1 = _Tp1; _Tp = TracerouteResults]
    operator=(shared_ptr<_Tp1>&& __r) noexcept
    ^
  /usr/include/c++/4.8.2/bits/shared_ptr.h:297:2: note:   template argument deduction/substitution failed:
  dublintraceroute/py3/_dublintraceroute.cc:94:11: note:   ‘TracerouteResults’ is not derived from ‘std::shared_ptr<_Tp1>’
     results = dublintraceroute->traceroute();
             ^
  In file included from /usr/include/c++/4.8.2/memory:82:0,
                   from /usr/include/c++/4.8.2/thread:40,
                   from /usr/include/dublintraceroute/dublin_traceroute.h:19,
                   from dublintraceroute/py3/_dublintraceroute.cc:4:
  /usr/include/c++/4.8.2/bits/shared_ptr.h:305:2: note: template<class _Tp1, class _Del> std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Tp1 = _Tp1; _Del = _Del; _Tp = TracerouteResults]
    operator=(std::unique_ptr<_Tp1, _Del>&& __r)
    ^
  /usr/include/c++/4.8.2/bits/shared_ptr.h:305:2: note:   template argument deduction/substitution failed:
  dublintraceroute/py3/_dublintraceroute.cc:94:11: note:   ‘TracerouteResults’ is not derived from ‘std::unique_ptr<_Tp, _Dp>’
     results = dublintraceroute->traceroute();
             ^
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for dublintraceroute
  Running setup.py clean for dublintraceroute
Failed to build dublintraceroute
Installing collected packages: dublintraceroute
  Running setup.py install for dublintraceroute ... error
    Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9fw10nzg/dublintraceroute/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0mymfbe_/install-record.txt --single-version-externally-managed --compile:
    /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/dublintraceroute
    copying dublintraceroute/tracerouteresults.py -> build/lib.linux-x86_64-3.6/dublintraceroute
    copying dublintraceroute/__init__.py -> build/lib.linux-x86_64-3.6/dublintraceroute
    copying dublintraceroute/dublintraceroute.py -> build/lib.linux-x86_64-3.6/dublintraceroute
    copying dublintraceroute/__main__.py -> build/lib.linux-x86_64-3.6/dublintraceroute
    running build_ext
    building 'dublintraceroute._dublintraceroute' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/dublintraceroute
    creating build/temp.linux-x86_64-3.6/dublintraceroute/py3
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../include -I/usr/include/jsoncpp -I/usr/local/include/python3.6m -c dublintraceroute/py3/_dublintraceroute.cc -o build/temp.linux-x86_64-3.6/dublintraceroute/py3/_dublintraceroute.o -std=c++11 -ldublintraceroute
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    dublintraceroute/py3/_dublintraceroute.cc: In function ‘PyObject* DublinTraceroute_traceroute(PyObject*, PyObject*)’:
    dublintraceroute/py3/_dublintraceroute.cc:94:11: error: no match for ‘operator=’ (operand types are ‘std::shared_ptr<TracerouteResults>’ and ‘TracerouteResults’)
       results = dublintraceroute->traceroute();
               ^
    dublintraceroute/py3/_dublintraceroute.cc:94:11: note: candidates are:
    In file included from /usr/include/c++/4.8.2/memory:82:0,
                     from /usr/include/c++/4.8.2/thread:40,
                     from /usr/include/dublintraceroute/dublin_traceroute.h:19,
                     from dublintraceroute/py3/_dublintraceroute.cc:4:
    /usr/include/c++/4.8.2/bits/shared_ptr.h:268:19: note: std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = TracerouteResults]
           shared_ptr& operator=(const shared_ptr&) noexcept = default;
                       ^
    /usr/include/c++/4.8.2/bits/shared_ptr.h:268:19: note:   no known conversion for argument 1 from ‘TracerouteResults’ to ‘const std::shared_ptr<TracerouteResults>&’
    /usr/include/c++/4.8.2/bits/shared_ptr.h:272:2: note: template<class _Tp1> std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp1>&) [with _Tp1 = _Tp1; _Tp = TracerouteResults]
      operator=(const shared_ptr<_Tp1>& __r) noexcept
      ^
    /usr/include/c++/4.8.2/bits/shared_ptr.h:272:2: note:   template argument deduction/substitution failed:
    dublintraceroute/py3/_dublintraceroute.cc:94:11: note:   ‘TracerouteResults’ is not derived from ‘const std::shared_ptr<_Tp1>’
       results = dublintraceroute->traceroute();
               ^
    In file included from /usr/include/c++/4.8.2/memory:82:0,
                     from /usr/include/c++/4.8.2/thread:40,
                     from /usr/include/dublintraceroute/dublin_traceroute.h:19,
                     from dublintraceroute/py3/_dublintraceroute.cc:4:
    /usr/include/c++/4.8.2/bits/shared_ptr.h:281:2: note: template<class _Tp1> std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Tp1 = _Tp1; _Tp = TracerouteResults]
      operator=(std::auto_ptr<_Tp1>&& __r)
      ^
    /usr/include/c++/4.8.2/bits/shared_ptr.h:281:2: note:   template argument deduction/substitution failed:
    dublintraceroute/py3/_dublintraceroute.cc:94:11: note:   ‘TracerouteResults’ is not derived from ‘std::auto_ptr<_Up>’
       results = dublintraceroute->traceroute();
               ^
    In file included from /usr/include/c++/4.8.2/memory:82:0,
                     from /usr/include/c++/4.8.2/thread:40,
                     from /usr/include/dublintraceroute/dublin_traceroute.h:19,
                     from dublintraceroute/py3/_dublintraceroute.cc:4:
    /usr/include/c++/4.8.2/bits/shared_ptr.h:289:7: note: std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = TracerouteResults]
           operator=(shared_ptr&& __r) noexcept
           ^
    /usr/include/c++/4.8.2/bits/shared_ptr.h:289:7: note:   no known conversion for argument 1 from ‘TracerouteResults’ to ‘std::shared_ptr<TracerouteResults>&&’
    /usr/include/c++/4.8.2/bits/shared_ptr.h:297:2: note: template<class _Tp1> std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp1>&&) [with _Tp1 = _Tp1; _Tp = TracerouteResults]
      operator=(shared_ptr<_Tp1>&& __r) noexcept
      ^
    /usr/include/c++/4.8.2/bits/shared_ptr.h:297:2: note:   template argument deduction/substitution failed:
    dublintraceroute/py3/_dublintraceroute.cc:94:11: note:   ‘TracerouteResults’ is not derived from ‘std::shared_ptr<_Tp1>’
       results = dublintraceroute->traceroute();
               ^
    In file included from /usr/include/c++/4.8.2/memory:82:0,
                     from /usr/include/c++/4.8.2/thread:40,
                     from /usr/include/dublintraceroute/dublin_traceroute.h:19,
                     from dublintraceroute/py3/_dublintraceroute.cc:4:
    /usr/include/c++/4.8.2/bits/shared_ptr.h:305:2: note: template<class _Tp1, class _Del> std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Tp1 = _Tp1; _Del = _Del; _Tp = TracerouteResults]
      operator=(std::unique_ptr<_Tp1, _Del>&& __r)
      ^
    /usr/include/c++/4.8.2/bits/shared_ptr.h:305:2: note:   template argument deduction/substitution failed:
    dublintraceroute/py3/_dublintraceroute.cc:94:11: note:   ‘TracerouteResults’ is not derived from ‘std::unique_ptr<_Tp, _Dp>’
       results = dublintraceroute->traceroute();
               ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9fw10nzg/dublintraceroute/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0mymfbe_/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-9fw10nzg/dublintraceroute/

------------------------------------------
python --version
Python 3.6.0a1

uname -a
Linux  3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by insomniacslk** [comment] 2018-04-24 22:04
this was probably broken by https://github.com/insomniacslk/dublin-traceroute/commit/95a707ab256fc13b72f239594ad222bd34cf4592 . I have to adapt the wrapper for python and upload a new release

**Comment by insomniacslk** [comment] 2018-04-25 08:55
@c2210691884 what is the version of dublin-traceroute (the C++ library) that you have installed?

**Comment by insomniacslk** [comment] 2018-04-25 08:59
the issue was actually already addressed in 06a607525aebd09f9727bc5567141ca2ec675887 .

@c2210691884 can you try to build from source and let me know? Just git clone this repo and run python3 setup.py build . I can't reproduce here

**Comment by insomniacslk** [comment] 2018-05-11 14:31
I'll close this. Feel free to reopen if the issue is not resolved for you

**Closed as completed by insomniacslk** 2018-05-11 14:31 UTC
